# Generated by Django 4.0.1 on 2022-03-23 17:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alfa_Carto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npn', models.CharField(max_length=30)),
                ('numero_predial', models.CharField(max_length=20, null=True)),
                ('comienzo_vida_util', models.DateField(null=True)),
                ('fin_vida_util', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Construcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npn', models.CharField(max_length=30)),
                ('numero_predial', models.CharField(max_length=20, null=True)),
                ('tipo_construccion', models.TextField(null=True)),
                ('area_digitada', models.FloatField(null=True)),
                ('area_cartografica', models.FloatField(null=True)),
                ('comienzo_vida_util', models.DateField(null=True)),
                ('fin_vida_util', models.DateField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4686)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npn', models.CharField(max_length=30)),
                ('numero_predial', models.CharField(max_length=20, null=True)),
                ('destino', models.TextField()),
                ('orip', models.CharField(max_length=3, null=True)),
                ('matricula', models.TextField(null=True)),
                ('area_terreno_digitada', models.FloatField(null=True)),
                ('area_construida_digitada', models.FloatField(null=True)),
                ('municipio', models.TextField()),
                ('departamento', models.TextField()),
                ('estado', models.IntegerField()),
                ('direccion', models.TextField(null=True)),
                ('vigencia', models.IntegerField()),
                ('comienzo_vida_util', models.DateField(null=True)),
                ('fin_vida_util', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.CharField(max_length=21)),
                ('fecha_resolucion', models.DateField()),
                ('sade', models.FloatField()),
                ('comienzo_vida_util', models.DateField()),
                ('fin_vida_util', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npn', models.CharField(max_length=30)),
                ('numero_predial', models.CharField(max_length=20, null=True)),
                ('area_digitada', models.FloatField()),
                ('area_cartografica', models.FloatField(null=True)),
                ('comienzo_vida_util', models.DateField()),
                ('fin_vida_util', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4686)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npn', models.CharField(max_length=30)),
                ('numero_predial', models.CharField(max_length=20, null=True)),
                ('identificador', models.CharField(max_length=4, null=True)),
                ('planta_ubicacion', models.IntegerField(null=True)),
                ('total_habitaciones', models.IntegerField(null=True)),
                ('total_banios', models.IntegerField(null=True)),
                ('total_locales', models.IntegerField(null=True)),
                ('total_pisos', models.IntegerField(null=True)),
                ('anio_construccion', models.IntegerField(null=True)),
                ('avaluo', models.IntegerField(null=True)),
                ('area_construida', models.FloatField(null=True)),
                ('area_cartografica', models.FloatField(null=True)),
                ('uso', models.TextField(null=True)),
                ('comienzo_vida_util', models.DateField(null=True)),
                ('fin_vida_util', models.DateField(null=True)),
                ('construccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.construcciones')),
            ],
        ),
        migrations.CreateModel(
            name='Terreno_Zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npn', models.CharField(max_length=30)),
                ('numero_predial', models.CharField(max_length=20, null=True)),
                ('area_digitada', models.FloatField()),
                ('zhf', models.IntegerField()),
                ('zhg', models.IntegerField()),
                ('area_cartografica', models.FloatField(null=True)),
                ('comienzo_vida_util', models.DateField(null=True)),
                ('fin_vida_util', models.DateField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4686)),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.terreno')),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion_Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutacion', models.TextField()),
                ('retira', models.CharField(max_length=1)),
                ('tipo_resolucion', models.TextField()),
                ('comienzo_vida_util', models.DateField()),
                ('fin_vida_util', models.DateField()),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.predio')),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.resolucion')),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion_Historica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion_cancela', models.IntegerField()),
                ('comienzo_vida_util', models.DateField()),
                ('fin_vida_util', models.DateField()),
                ('alfa_carto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.alfa_carto')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.predio')),
                ('resolucion_predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.resolucion_predio')),
            ],
        ),
        migrations.CreateModel(
            name='Predio_Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.TextField()),
                ('descripcion', models.TextField()),
                ('comienzo_vida_util', models.DateField()),
                ('fin_vida_util', models.DateField()),
                ('vigencia', models.IntegerField()),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.predio')),
            ],
        ),
        migrations.AddField(
            model_name='alfa_carto',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.predio'),
        ),
        migrations.AddField(
            model_name='alfa_carto',
            name='terreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.terreno'),
        ),
        migrations.AddField(
            model_name='alfa_carto',
            name='unidades_construccion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovisor.unidades'),
        ),
    ]
