# Generated by Django 4.0.1 on 2022-03-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0005_rename_unidades_construccion_id_alfa_carto_unidades_construccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='numero_predial',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
