# Generated by Django 4.0.1 on 2022-03-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0006_alter_unidades_numero_predial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='avaluo',
            field=models.FloatField(null=True),
        ),
    ]
