# Generated by Django 4.0.1 on 2022-03-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0009_alter_alfa_carto_npn_alter_alfa_carto_predio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='departamento',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='predio',
            name='destino',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='predio',
            name='estado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='predio',
            name='municipio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='predio',
            name='vigencia',
            field=models.IntegerField(null=True),
        ),
    ]
