# Generated by Django 4.0.1 on 2022-03-24 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0011_alter_alfa_carto_terreno_alter_construcciones_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno_zonas',
            name='terreno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geovisor.terreno'),
        ),
    ]
