# Generated by Django 4.0.1 on 2022-03-26 14:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0012_alter_terreno_zonas_terreno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.TextField(null=True)),
                ('departamento', models.TextField(null=True)),
                ('asignados', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4686)),
            ],
        ),
    ]
