# Generated by Django 4.0.1 on 2022-04-28 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0014_predio_area_cartografica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construcciones',
            name='unidades',
        ),
        migrations.AddField(
            model_name='unidades',
            name='construcciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geovisor.construcciones'),
        ),
    ]
