# Generated by Django 4.0.1 on 2022-05-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0015_remove_construcciones_unidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alfa_carto',
            name='construcciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geovisor.construcciones'),
        ),
    ]
