# Generated by Django 4.0.1 on 2022-05-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0016_alfa_carto_construcciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidades',
            name='construcciones',
        ),
    ]
