# Generated by Django 4.0.1 on 2023-11-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0017_remove_unidades_construcciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alfa_carto',
            name='construcciones',
        ),
        migrations.RemoveField(
            model_name='alfa_carto',
            name='predio',
        ),
        migrations.RemoveField(
            model_name='alfa_carto',
            name='terreno',
        ),
        migrations.RemoveField(
            model_name='alfa_carto',
            name='unidades_construccion',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.RemoveField(
            model_name='predio_proceso',
            name='predio',
        ),
        migrations.RemoveField(
            model_name='resolucion_historica',
            name='alfa_carto',
        ),
        migrations.RemoveField(
            model_name='resolucion_historica',
            name='predio',
        ),
        migrations.RemoveField(
            model_name='resolucion_historica',
            name='resolucion_predio',
        ),
        migrations.RemoveField(
            model_name='resolucion_predio',
            name='predio',
        ),
        migrations.RemoveField(
            model_name='resolucion_predio',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='terreno_zonas',
            name='terreno',
        ),
        migrations.DeleteModel(
            name='Alfa_Carto',
        ),
        migrations.DeleteModel(
            name='Construcciones',
        ),
        migrations.DeleteModel(
            name='Predio_Proceso',
        ),
        migrations.DeleteModel(
            name='Resolucion',
        ),
        migrations.DeleteModel(
            name='Resolucion_Historica',
        ),
        migrations.DeleteModel(
            name='Resolucion_Predio',
        ),
        migrations.DeleteModel(
            name='Terreno_Zonas',
        ),
    ]
