# Generated by Django 4.0.1 on 2023-11-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0018_remove_alfa_carto_construcciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='laura',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
