# Generated by Django 4.0.1 on 2023-11-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0019_terreno_laura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terreno',
            name='laura',
        ),
    ]
