# Generated by Django 4.0.1 on 2023-11-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0020_remove_terreno_laura'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='laura',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
