# Generated by Django 4.0.1 on 2023-11-21 00:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0022_remove_terreno_laura'),
    ]

    operations = [
        migrations.CreateModel(
            name='construccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npn', models.CharField(max_length=30)),
                ('numero_predial', models.CharField(max_length=40, null=True)),
                ('identificador', models.TextField(null=True)),
                ('planta_ubicacion', models.IntegerField(null=True)),
                ('total_habitaciones', models.IntegerField(null=True)),
                ('total_banios', models.IntegerField(null=True)),
                ('total_locales', models.IntegerField(null=True)),
                ('total_pisos', models.IntegerField(null=True)),
                ('anio_construccion', models.IntegerField(null=True)),
                ('avaluo', models.FloatField(null=True)),
                ('area_construida', models.FloatField(null=True)),
                ('area_cartografica', models.FloatField(null=True)),
                ('uso', models.TextField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Unidades',
        ),
        migrations.RenameField(
            model_name='predio',
            old_name='destino',
            new_name='Tipo',
        ),
        migrations.RenameField(
            model_name='predio',
            old_name='matricula',
            new_name='destinacion_economica',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='area_cartografica',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='area_construida_digitada',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='area_terreno_digitada',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='comienzo_vida_util',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='fin_vida_util',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='orip',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='vigencia',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='comienzo_vida_util',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='fin_vida_util',
        ),
        migrations.AlterField(
            model_name='terreno',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
