# Generated by Django 4.0.1 on 2023-11-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0023_construccion_delete_unidades_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='construccion',
            old_name='anio_construccion',
            new_name='numero_mezanines',
        ),
        migrations.RenameField(
            model_name='construccion',
            old_name='planta_ubicacion',
            new_name='numero_pisos',
        ),
        migrations.RenameField(
            model_name='construccion',
            old_name='total_banios',
            new_name='numero_semisotanos',
        ),
        migrations.RenameField(
            model_name='construccion',
            old_name='total_habitaciones',
            new_name='numero_sotanos',
        ),
        migrations.RenameField(
            model_name='construccion',
            old_name='uso',
            new_name='tipo_construccion',
        ),
        migrations.RenameField(
            model_name='predio',
            old_name='Tipo',
            new_name='clase_suelo',
        ),
        migrations.RenameField(
            model_name='predio',
            old_name='departamento',
            new_name='condicion',
        ),
        migrations.RenameField(
            model_name='predio',
            old_name='municipio',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='construccion',
            name='area_cartografica',
        ),
        migrations.RemoveField(
            model_name='construccion',
            name='avaluo',
        ),
        migrations.RemoveField(
            model_name='construccion',
            name='total_locales',
        ),
        migrations.RemoveField(
            model_name='construccion',
            name='total_pisos',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='area_cartografica',
        ),
        migrations.AddField(
            model_name='construccion',
            name='tipo_dominio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='terreno',
            name='codigo_manzana',
            field=models.TextField(null=True),
        ),
    ]
